// Kernel Function: kernel_qk_matmul
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>
#include <pto/pto-inst.hpp>
#include "tensor.h"

using namespace pto;

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#define __aicore__ [aicore]
#endif


// --- ptoas-generated code ---
static __aicore__ void kernel_qk_matmul(__gm__ bfloat16_t* v1, __gm__ bfloat16_t* v2, __gm__ float* v3) {
  unsigned v4 = 2048;
  unsigned v5 = 128;
  unsigned v6 = 16;
  unsigned v7 = 1;
  unsigned v8 = 0;
  int32_t v9 = 1;
  int32_t v10 = 128;
  int32_t v11 = 16;
  int64_t v12 = 0;
  int64_t v13 = 4096;
  using T = float;
  Tile<TileType::Mat, bfloat16_t, 16, 128, BLayout::ColMajor, 16, 128, SLayout::RowMajor, 512, PadValue::Null> v14;
  TASSIGN(v14, v12);
  Tile<TileType::Mat, bfloat16_t, 128, 128, BLayout::RowMajor, 128, 128, SLayout::ColMajor, 512, PadValue::Null> v15;
  TASSIGN(v15, v13);
  Tile<TileType::Left, bfloat16_t, 16, 128, BLayout::ColMajor, 16, 128, SLayout::RowMajor, 512, PadValue::Null> v16;
  TASSIGN(v16, v12);
  Tile<TileType::Right, bfloat16_t, 128, 128, BLayout::RowMajor, 128, 128, SLayout::ColMajor, 512, PadValue::Null> v17;
  TASSIGN(v17, v12);
  Tile<TileType::Acc, float, 16, 128, BLayout::ColMajor, 16, 128, SLayout::RowMajor, 1024, PadValue::Null> v18;
  TASSIGN(v18, v12);
  pto::Shape<1, 1, 1, 16, 128> v19 = pto::Shape<1, 1, 1, 16, 128>();
  pto::Stride<2048, 2048, 2048, 128, 1> v20 = pto::Stride<2048, 2048, 2048, 128, 1>();
  GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 128>, pto::Stride<2048, 2048, 2048, 128, 1>, pto::Layout::ND> v21 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 128>, pto::Stride<2048, 2048, 2048, 128, 1>, pto::Layout::ND>(v1 + (v8 + v8 * (unsigned) v10 + v8 * (unsigned) v9), v19, v20);
  TLOAD(v14, v21);
  set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID0);
  pto::Shape<1, 1, 1, 128, 128> v22 = pto::Shape<1, 1, 1, 128, 128>();
  pto::Stride<128, 128, 128, 1, 128> v23 = pto::Stride<128, 128, 128, 1, 128>();
  GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 128, 128>, pto::Stride<128, 128, 128, 1, 128>, pto::Layout::DN> v24 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 128, 128>, pto::Stride<128, 128, 128, 1, 128>, pto::Layout::DN>(v2 + (v8 + v8 * (unsigned) v9 + v8 * (unsigned) v10), v22, v23);
  TLOAD(v15, v24);
  set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID1);
  wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID0);
  TMOV(v16, v14);
  wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID1);
  TMOV(v17, v15);
  set_flag(PIPE_MTE1, PIPE_M, EVENT_ID0);
  wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID0);
  TMATMUL(v18, v16, v17);
  set_flag(PIPE_M, PIPE_FIX, EVENT_ID0);
  pto::Shape<1, 1, 1, 16, 128> v25 = pto::Shape<1, 1, 1, 16, 128>();
  pto::Stride<2048, 2048, 2048, 128, 1> v26 = pto::Stride<2048, 2048, 2048, 128, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 128>, pto::Stride<2048, 2048, 2048, 128, 1>, pto::Layout::ND> v27 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 128>, pto::Stride<2048, 2048, 2048, 128, 1>, pto::Layout::ND>(v3 + (v8 + v8 * (unsigned) v10 + v8 * (unsigned) v9), v25, v26);
  wait_flag(PIPE_M, PIPE_FIX, EVENT_ID0);
  TSTORE(v27, v18);
  pipe_barrier(PIPE_ALL);
  return;
}


// --- CCE-compatible entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: qi_0
    __gm__ TensorData* qi_0_tensor = reinterpret_cast<__gm__ TensorData*>(args[0]);
    __gm__ bfloat16_t* qi_0 = reinterpret_cast<__gm__ bfloat16_t*>(qi_0_tensor->buffer.addr) + qi_0_tensor->start_offset;

    // Unpack tensor: kj_0
    __gm__ TensorData* kj_0_tensor = reinterpret_cast<__gm__ TensorData*>(args[1]);
    __gm__ bfloat16_t* kj_0 = reinterpret_cast<__gm__ bfloat16_t*>(kj_0_tensor->buffer.addr) + kj_0_tensor->start_offset;

    // Unpack tensor: output_0
    __gm__ TensorData* output_0_tensor = reinterpret_cast<__gm__ TensorData*>(args[2]);
    __gm__ float* output_0 = reinterpret_cast<__gm__ float*>(output_0_tensor->buffer.addr) + output_0_tensor->start_offset;

    // Forward to ptoas-generated function
    kernel_qk_matmul(qi_0, kj_0, output_0);
}
