// Kernel Function: kernel_softmax_prepare
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>
#include <pto/pto-inst.hpp>
#include "tensor.h"

using namespace pto;

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#define __aicore__ [aicore]
#endif


// --- ptoas-generated code ---
static __aicore__ void kernel_softmax_prepare(__gm__ float* v1, float v2, __gm__ bfloat16_t* v3, __gm__ float* v4, __gm__ float* v5) {
  RoundMode v6 = RoundMode::CAST_ROUND;
  unsigned v7 = 2048;
  unsigned v8 = 128;
  unsigned v9 = 16;
  unsigned v10 = 1;
  unsigned v11 = 0;
  int32_t v12 = 1;
  int32_t v13 = 128;
  int32_t v14 = 16;
  int64_t v15 = 0;
  int64_t v16 = 8192;
  int64_t v17 = 16384;
  int64_t v18 = 16448;
  int64_t v19 = 24640;
  int64_t v20 = 28736;
  int64_t v21 = 36928;
  using T = float;
  Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, 16, 128, SLayout::NoneBox, 512, PadValue::Null> v22;
  TASSIGN(v22, v15);
  Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, 16, 128, SLayout::NoneBox, 512, PadValue::Null> v23;
  TASSIGN(v23, v16);
  Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, 16, 1, SLayout::NoneBox, 512, PadValue::Null> v24;
  TASSIGN(v24, v17);
  Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, 16, 128, SLayout::NoneBox, 512, PadValue::Null> v25;
  TASSIGN(v25, v18);
  Tile<TileType::Vec, bfloat16_t, 16, 128, BLayout::RowMajor, 16, 128, SLayout::NoneBox, 512, PadValue::Null> v26;
  TASSIGN(v26, v19);
  Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, 16, 128, SLayout::NoneBox, 512, PadValue::Null> v27;
  TASSIGN(v27, v20);
  Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, 16, 1, SLayout::NoneBox, 512, PadValue::Null> v28;
  TASSIGN(v28, v21);
  pto::Shape<1, 1, 1, 16, 128> v29 = pto::Shape<1, 1, 1, 16, 128>();
  pto::Stride<2048, 2048, 2048, 128, 1> v30 = pto::Stride<2048, 2048, 2048, 128, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 128>, pto::Stride<2048, 2048, 2048, 128, 1>, pto::Layout::ND> v31 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 128>, pto::Stride<2048, 2048, 2048, 128, 1>, pto::Layout::ND>(v1 + (v11 + v11 * (unsigned) v13 + v11 * (unsigned) v12), v29, v30);
  TLOAD(v22, v31);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  TMULS(v23, v22, v2);
  pipe_barrier(PIPE_V);
  TROWMAX(v24, v23, v22);
  pipe_barrier(PIPE_V);
  TROWEXPANDSUB(v25, v23, v24);
  pipe_barrier(PIPE_V);
  TEXP(v23, v25);
  pipe_barrier(PIPE_V);
  TCVT(v26, v23, v6);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  pipe_barrier(PIPE_V);
  TCVT(v27, v26, v6);
  pipe_barrier(PIPE_V);
  TROWSUM(v28, v27, v22);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
  pto::Shape<1, 1, 1, 16, 128> v32 = pto::Shape<1, 1, 1, 16, 128>();
  pto::Stride<2048, 2048, 2048, 128, 1> v33 = pto::Stride<2048, 2048, 2048, 128, 1>();
  GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 128>, pto::Stride<2048, 2048, 2048, 128, 1>, pto::Layout::ND> v34 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 128>, pto::Stride<2048, 2048, 2048, 128, 1>, pto::Layout::ND>(v3 + (v11 + v11 * (unsigned) v13 + v11 * (unsigned) v12), v32, v33);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  TSTORE(v34, v26);
  pto::Shape<1, 1, 1, 16, 1> v35 = pto::Shape<1, 1, 1, 16, 1>();
  pto::Stride<16, 16, 16, 1, 1> v36 = pto::Stride<16, 16, 16, 1, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<16, 16, 16, 1, 1>, pto::Layout::DN> v37 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<16, 16, 16, 1, 1>, pto::Layout::DN>(v4 + (v11 + v11 * (unsigned) v12 + v11 * (unsigned) v12), v35, v36);
  TSTORE(v37, v24);
  pto::Shape<1, 1, 1, 16, 1> v38 = pto::Shape<1, 1, 1, 16, 1>();
  pto::Stride<16, 16, 16, 1, 1> v39 = pto::Stride<16, 16, 16, 1, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<16, 16, 16, 1, 1>, pto::Layout::DN> v40 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<16, 16, 16, 1, 1>, pto::Layout::DN>(v5 + (v11 + v11 * (unsigned) v12 + v11 * (unsigned) v12), v38, v39);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
  TSTORE(v40, v28);
  pipe_barrier(PIPE_ALL);
  return;
}


// --- CCE-compatible entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: sij_0
    __gm__ TensorData* sij_0_tensor = reinterpret_cast<__gm__ TensorData*>(args[0]);
    __gm__ float* sij_0 = reinterpret_cast<__gm__ float*>(sij_0_tensor->buffer.addr) + sij_0_tensor->start_offset;

    // Unpack scalar: scale_0
    union { uint64_t u64; float val; } scale_0_conv;
    scale_0_conv.u64 = args[1];
    float scale_0 = scale_0_conv.val;

    // Unpack tensor: out_pij_0
    __gm__ TensorData* out_pij_0_tensor = reinterpret_cast<__gm__ TensorData*>(args[2]);
    __gm__ bfloat16_t* out_pij_0 = reinterpret_cast<__gm__ bfloat16_t*>(out_pij_0_tensor->buffer.addr) + out_pij_0_tensor->start_offset;

    // Unpack tensor: out_mi_0
    __gm__ TensorData* out_mi_0_tensor = reinterpret_cast<__gm__ TensorData*>(args[3]);
    __gm__ float* out_mi_0 = reinterpret_cast<__gm__ float*>(out_mi_0_tensor->buffer.addr) + out_mi_0_tensor->start_offset;

    // Unpack tensor: out_li_0
    __gm__ TensorData* out_li_0_tensor = reinterpret_cast<__gm__ TensorData*>(args[4]);
    __gm__ float* out_li_0 = reinterpret_cast<__gm__ float*>(out_li_0_tensor->buffer.addr) + out_li_0_tensor->start_offset;

    // Forward to ptoas-generated function
    kernel_softmax_prepare(sij_0, scale_0, out_pij_0, out_mi_0, out_li_0);
}
