// Kernel Function: kernel_init_inplace
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>
#include <pto/pto-inst.hpp>
#include "tensor.h"

using namespace pto;

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#define __aicore__ [aicore]
#endif


// --- ptoas-generated code ---
static __aicore__ void kernel_init_inplace(__gm__ float* v1, __gm__ float* v2, __gm__ float* v3) {
  using T = float;
  return;
}


// --- CCE-compatible entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: oi_0
    __gm__ TensorData* oi_0_tensor = reinterpret_cast<__gm__ TensorData*>(args[0]);
    __gm__ float* oi_0 = reinterpret_cast<__gm__ float*>(oi_0_tensor->buffer.addr) + oi_0_tensor->start_offset;

    // Unpack tensor: li_0
    __gm__ TensorData* li_0_tensor = reinterpret_cast<__gm__ TensorData*>(args[1]);
    __gm__ float* li_0 = reinterpret_cast<__gm__ float*>(li_0_tensor->buffer.addr) + li_0_tensor->start_offset;

    // Unpack tensor: mi_0
    __gm__ TensorData* mi_0_tensor = reinterpret_cast<__gm__ TensorData*>(args[2]);
    __gm__ float* mi_0 = reinterpret_cast<__gm__ float*>(mi_0_tensor->buffer.addr) + mi_0_tensor->start_offset;

    // Forward to ptoas-generated function
    kernel_init_inplace(oi_0, li_0, mi_0);
}
