// Kernel Function: kernel_init_inplace
// Generated by PyPTO IR Compiler


#include <cstdint>
#include <pto/pto-inst.hpp>
#include "tensor.h"

using namespace pto;

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#define __aicore__ [aicore]
#endif

// Helper function to compute stride from raw_shapes
__aicore__ __attribute__((always_inline)) inline int64_t compute_stride(
    __gm__ TensorData* tensor, int dim) {
  int64_t stride = 1;
  for (int j = dim + 1; j < static_cast<int>(tensor->ndims); j++) {
    stride *= static_cast<int64_t>(tensor->raw_shapes[j]);
  }
  return stride;
}

extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack arguments and type declarations
    __gm__ TensorData* oi_0_tensor = reinterpret_cast<__gm__ TensorData*>(args[0]);
    __gm__ float* oi_0 = reinterpret_cast<__gm__ float*>(oi_0_tensor->buffer.addr) + oi_0_tensor->start_offset;

    __gm__ TensorData* li_0_tensor = reinterpret_cast<__gm__ TensorData*>(args[1]);
    __gm__ float* li_0 = reinterpret_cast<__gm__ float*>(li_0_tensor->buffer.addr) + li_0_tensor->start_offset;

    __gm__ TensorData* mi_0_tensor = reinterpret_cast<__gm__ TensorData*>(args[2]);
    __gm__ float* mi_0 = reinterpret_cast<__gm__ float*>(mi_0_tensor->buffer.addr) + mi_0_tensor->start_offset;


    // Function body
}
