// Kernel Function: kernel_softmax_prepare
// Generated by PyPTO IR Compiler


#include <cstdint>
#include <pto/pto-inst.hpp>
#include "tensor.h"

using namespace pto;

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#define __aicore__ [aicore]
#endif

// Helper function to compute stride from raw_shapes
__aicore__ __attribute__((always_inline)) inline int64_t compute_stride(
    __gm__ TensorData* tensor, int dim) {
  int64_t stride = 1;
  for (int j = dim + 1; j < static_cast<int>(tensor->ndims); j++) {
    stride *= static_cast<int64_t>(tensor->raw_shapes[j]);
  }
  return stride;
}

extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack arguments and type declarations
    __gm__ TensorData* sij_0_tensor = reinterpret_cast<__gm__ TensorData*>(args[0]);
    __gm__ float* sij_0 = reinterpret_cast<__gm__ float*>(sij_0_tensor->buffer.addr) + sij_0_tensor->start_offset;

    union { uint64_t u64; float val; } scale_0_conv;
    scale_0_conv.u64 = args[1];
    float scale_0 = scale_0_conv.val;

    __gm__ TensorData* out_pij_0_tensor = reinterpret_cast<__gm__ TensorData*>(args[2]);
    __gm__ bfloat16_t* out_pij_0 = reinterpret_cast<__gm__ bfloat16_t*>(out_pij_0_tensor->buffer.addr) + out_pij_0_tensor->start_offset;

    __gm__ TensorData* out_mi_0_tensor = reinterpret_cast<__gm__ TensorData*>(args[3]);
    __gm__ float* out_mi_0 = reinterpret_cast<__gm__ float*>(out_mi_0_tensor->buffer.addr) + out_mi_0_tensor->start_offset;

    __gm__ TensorData* out_li_0_tensor = reinterpret_cast<__gm__ TensorData*>(args[4]);
    __gm__ float* out_li_0 = reinterpret_cast<__gm__ float*>(out_li_0_tensor->buffer.addr) + out_li_0_tensor->start_offset;

    // Tile type definitions and allocations
    using s_tile_0Type = Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512>;
    s_tile_0Type s_tile_0(16, 128);
    TASSIGN(s_tile_0, 0x0);
    using scaled_0Type = Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512>;
    scaled_0Type scaled_0(16, 128);
    TASSIGN(scaled_0, 0x2000);
    using tmp_tile_0Type = Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512>;
    tmp_tile_0Type tmp_tile_0(16, 128);
    TASSIGN(tmp_tile_0, 0x0);
    using mi_tile_0Type = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512>;
    mi_tile_0Type mi_tile_0(16, 1);
    TASSIGN(mi_tile_0, 0x4000);
    using sij_centered_0Type = Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512>;
    sij_centered_0Type sij_centered_0(16, 128);
    TASSIGN(sij_centered_0, 0x4040);
    using exp_tile_0Type = Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512>;
    exp_tile_0Type exp_tile_0(16, 128);
    TASSIGN(exp_tile_0, 0x2000);
    using pij_tile_bf16_0Type = Tile<TileType::Vec, bfloat16_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512>;
    pij_tile_bf16_0Type pij_tile_bf16_0(16, 128);
    TASSIGN(pij_tile_bf16_0, 0x6040);
    using pij_tile_0Type = Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512>;
    pij_tile_0Type pij_tile_0(16, 128);
    TASSIGN(pij_tile_0, 0x7040);
    using li_tile_0Type = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512>;
    li_tile_0Type li_tile_0(16, 1);
    TASSIGN(li_tile_0, 0x9040);


    // Function body
    using tmp_gm_0ShapeDim5 = Shape<1, 1, 1, 16, 128>;
    using tmp_gm_0StrideDim5 = Stride<1, 1, 1, -1, -1>;
    using tmp_gm_0Type = GlobalTensor<float, tmp_gm_0ShapeDim5, tmp_gm_0StrideDim5, Layout::ND>;
    tmp_gm_0Type tmp_gm_0(sij_0, {}, {compute_stride(sij_0_tensor, 0), compute_stride(sij_0_tensor, 1)});
    TASSIGN(tmp_gm_0, sij_0 + (0 + 0 * compute_stride(sij_0_tensor, 0) + 0 * compute_stride(sij_0_tensor, 1)));
    TLOAD(s_tile_0, tmp_gm_0);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    TMULS(scaled_0, s_tile_0, scale_0);
    pipe_barrier(PIPE_V);
    TROWMAX(mi_tile_0, scaled_0, tmp_tile_0);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    pipe_barrier(PIPE_V);
    TROWEXPANDSUB(sij_centered_0, scaled_0, mi_tile_0);
    pipe_barrier(PIPE_V);
    TEXP(exp_tile_0, sij_centered_0);
    pipe_barrier(PIPE_V);
    TCVT(pij_tile_bf16_0, exp_tile_0, RoundMode::CAST_ROUND);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
    pipe_barrier(PIPE_V);
    TCVT(pij_tile_0, pij_tile_bf16_0, RoundMode::CAST_ROUND);
    pipe_barrier(PIPE_V);
    TROWSUM(li_tile_0, pij_tile_0, tmp_tile_0);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID2);
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
    using tmp_gm_1ShapeDim5 = Shape<1, 1, 1, 16, 128>;
    using tmp_gm_1StrideDim5 = Stride<1, 1, 1, -1, -1>;
    using tmp_gm_1Type = GlobalTensor<bfloat16_t, tmp_gm_1ShapeDim5, tmp_gm_1StrideDim5, Layout::ND>;
    tmp_gm_1Type tmp_gm_1(out_pij_0, {}, {compute_stride(out_pij_0_tensor, 0), compute_stride(out_pij_0_tensor, 1)});
    TASSIGN(tmp_gm_1, out_pij_0 + (0 + 0 * compute_stride(out_pij_0_tensor, 0) + 0 * compute_stride(out_pij_0_tensor, 1)));
    TSTORE(tmp_gm_1, pij_tile_bf16_0);
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    using tmp_gm_2ShapeDim5 = Shape<1, 1, 1, 16, 1>;
    using tmp_gm_2StrideDim5 = Stride<1, 1, 1, -1, -1>;
    using tmp_gm_2Type = GlobalTensor<float, tmp_gm_2ShapeDim5, tmp_gm_2StrideDim5, Layout::ND>;
    tmp_gm_2Type tmp_gm_2(out_mi_0, {}, {compute_stride(out_mi_0_tensor, 0), compute_stride(out_mi_0_tensor, 1)});
    TASSIGN(tmp_gm_2, out_mi_0 + (0 + 0 * compute_stride(out_mi_0_tensor, 0) + 0 * compute_stride(out_mi_0_tensor, 1)));
    TSTORE(tmp_gm_2, mi_tile_0);
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID2);
    using tmp_gm_3ShapeDim5 = Shape<1, 1, 1, 16, 1>;
    using tmp_gm_3StrideDim5 = Stride<1, 1, 1, -1, -1>;
    using tmp_gm_3Type = GlobalTensor<float, tmp_gm_3ShapeDim5, tmp_gm_3StrideDim5, Layout::ND>;
    tmp_gm_3Type tmp_gm_3(out_li_0, {}, {compute_stride(out_li_0_tensor, 0), compute_stride(out_li_0_tensor, 1)});
    TASSIGN(tmp_gm_3, out_li_0 + (0 + 0 * compute_stride(out_li_0_tensor, 0) + 0 * compute_stride(out_li_0_tensor, 1)));
    TSTORE(tmp_gm_3, li_tile_0);
}
