// Kernel Function: kernel_online_update
// Generated by PyPTO IR Compiler


#include <cstdint>
#include <pto/pto-inst.hpp>
#include "tensor.h"

using namespace pto;

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#define __aicore__ [aicore]
#endif

// Helper function to compute stride from raw_shapes
__aicore__ __attribute__((always_inline)) inline int64_t compute_stride(
    __gm__ TensorData* tensor, int dim) {
  int64_t stride = 1;
  for (int j = dim + 1; j < static_cast<int>(tensor->ndims); j++) {
    stride *= static_cast<int64_t>(tensor->raw_shapes[j]);
  }
  return stride;
}

extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack arguments and type declarations
    __gm__ TensorData* mij_0_tensor = reinterpret_cast<__gm__ TensorData*>(args[0]);
    __gm__ float* mij_0 = reinterpret_cast<__gm__ float*>(mij_0_tensor->buffer.addr) + mij_0_tensor->start_offset;

    __gm__ TensorData* lij_0_tensor = reinterpret_cast<__gm__ TensorData*>(args[1]);
    __gm__ float* lij_0 = reinterpret_cast<__gm__ float*>(lij_0_tensor->buffer.addr) + lij_0_tensor->start_offset;

    __gm__ TensorData* oi_new_0_tensor = reinterpret_cast<__gm__ TensorData*>(args[2]);
    __gm__ float* oi_new_0 = reinterpret_cast<__gm__ float*>(oi_new_0_tensor->buffer.addr) + oi_new_0_tensor->start_offset;

    __gm__ TensorData* mi_0_tensor = reinterpret_cast<__gm__ TensorData*>(args[3]);
    __gm__ float* mi_0 = reinterpret_cast<__gm__ float*>(mi_0_tensor->buffer.addr) + mi_0_tensor->start_offset;

    __gm__ TensorData* li_0_tensor = reinterpret_cast<__gm__ TensorData*>(args[4]);
    __gm__ float* li_0 = reinterpret_cast<__gm__ float*>(li_0_tensor->buffer.addr) + li_0_tensor->start_offset;

    __gm__ TensorData* oi_0_tensor = reinterpret_cast<__gm__ TensorData*>(args[5]);
    __gm__ float* oi_0 = reinterpret_cast<__gm__ float*>(oi_0_tensor->buffer.addr) + oi_0_tensor->start_offset;

    __gm__ TensorData* dst_0_tensor = reinterpret_cast<__gm__ TensorData*>(args[6]);
    __gm__ float* dst_0 = reinterpret_cast<__gm__ float*>(dst_0_tensor->buffer.addr) + dst_0_tensor->start_offset;

    union { uint64_t u64; bool val; } is_first_0_conv;
    is_first_0_conv.u64 = args[7];
    bool is_first_0 = is_first_0_conv.val;

    union { uint64_t u64; bool val; } is_last_0_conv;
    is_last_0_conv.u64 = args[8];
    bool is_last_0 = is_last_0_conv.val;

    // Tile type definitions and allocations
    using mij_tile_0Type = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512>;
    mij_tile_0Type mij_tile_0(16, 1);
    TASSIGN(mij_tile_0, 0x0);
    using lij_tile_0Type = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512>;
    lij_tile_0Type lij_tile_0(16, 1);
    TASSIGN(lij_tile_0, 0x40);
    using oi_new_tile_0Type = Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512>;
    oi_new_tile_0Type oi_new_tile_0(16, 128);
    TASSIGN(oi_new_tile_0, 0x80);
    using mi_tile_0Type = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512>;
    mi_tile_0Type mi_tile_0(16, 1);
    TASSIGN(mi_tile_0, 0x2080);
    using li_tile_0Type = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512>;
    li_tile_0Type li_tile_0(16, 1);
    TASSIGN(li_tile_0, 0x20c0);
    using oi_tile_0Type = Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512>;
    oi_tile_0Type oi_tile_0(16, 128);
    TASSIGN(oi_tile_0, 0x2100);
    using dst_tile_0Type = Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512>;
    dst_tile_0Type dst_tile_0(16, 128);
    TASSIGN(dst_tile_0, 0x4100);
    using zero_tile_0Type = Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512>;
    zero_tile_0Type zero_tile_0(16, 128);
    TASSIGN(zero_tile_0, 0x4100);
    using mi_tile_nd_0Type = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512>;
    mi_tile_nd_0Type mi_tile_nd_0(1, 16);
    TASSIGN(mi_tile_nd_0, 0x2080);
    using mij_tile_nd_0Type = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512>;
    mij_tile_nd_0Type mij_tile_nd_0(1, 16);
    TASSIGN(mij_tile_nd_0, 0x0);
    using li_tile_nd_0Type = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512>;
    li_tile_nd_0Type li_tile_nd_0(1, 16);
    TASSIGN(li_tile_nd_0, 0x20c0);
    using lij_tile_nd_0Type = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512>;
    lij_tile_nd_0Type lij_tile_nd_0(1, 16);
    TASSIGN(lij_tile_nd_0, 0x40);
    using mi_new_0Type = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512>;
    mi_new_0Type mi_new_0(1, 16);
    TASSIGN(mi_new_0, 0x6100);
    using mi_diff_0Type = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512>;
    mi_diff_0Type mi_diff_0(1, 16);
    TASSIGN(mi_diff_0, 0x6140);
    using alpha_0Type = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512>;
    alpha_0Type alpha_0(1, 16);
    TASSIGN(alpha_0, 0x6180);
    using mij_diff_0Type = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512>;
    mij_diff_0Type mij_diff_0(1, 16);
    TASSIGN(mij_diff_0, 0x6140);
    using beta_0Type = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512>;
    beta_0Type beta_0(1, 16);
    TASSIGN(beta_0, 0x6200);
    using li_scaled_0Type = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512>;
    li_scaled_0Type li_scaled_0(1, 16);
    TASSIGN(li_scaled_0, 0x6140);
    using lij_scaled_0Type = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512>;
    lij_scaled_0Type lij_scaled_0(1, 16);
    TASSIGN(lij_scaled_0, 0x61c0);
    using li_updated_0Type = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512>;
    li_updated_0Type li_updated_0(1, 16);
    TASSIGN(li_updated_0, 0x6240);
    using alpha_dn_0Type = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512>;
    alpha_dn_0Type alpha_dn_0(16, 1);
    TASSIGN(alpha_dn_0, 0x6180);
    using oi_scaled_0Type = Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512>;
    oi_scaled_0Type oi_scaled_0(16, 128);
    TASSIGN(oi_scaled_0, 0x4100);
    using beta_dn_0Type = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512>;
    beta_dn_0Type beta_dn_0(16, 1);
    TASSIGN(beta_dn_0, 0x6200);
    using oi_new_scaled_0Type = Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512>;
    oi_new_scaled_0Type oi_new_scaled_0(16, 128);
    TASSIGN(oi_new_scaled_0, 0x2100);
    using oi_updated_0Type = Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512>;
    oi_updated_0Type oi_updated_0(16, 128);
    TASSIGN(oi_updated_0, 0x80);
    using mi_new_dn_0Type = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512>;
    mi_new_dn_0Type mi_new_dn_0(16, 1);
    TASSIGN(mi_new_dn_0, 0x6100);
    using li_updated_dn_0Type = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512>;
    li_updated_dn_0Type li_updated_dn_0(16, 1);
    TASSIGN(li_updated_dn_0, 0x6240);
    using dst_tile_1Type = Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512>;
    dst_tile_1Type dst_tile_1(16, 128);
    TASSIGN(dst_tile_1, 0x2100);
    using zero_tile_1Type = Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512>;
    zero_tile_1Type zero_tile_1(16, 128);
    TASSIGN(zero_tile_1, 0x2100);


    // Function body
    using tmp_gm_0ShapeDim5 = Shape<1, 1, 1, 16, 1>;
    using tmp_gm_0StrideDim5 = Stride<1, 1, 1, -1, -1>;
    using tmp_gm_0Type = GlobalTensor<float, tmp_gm_0ShapeDim5, tmp_gm_0StrideDim5, Layout::DN>;
    tmp_gm_0Type tmp_gm_0(mij_0, {}, {compute_stride(mij_0_tensor, 1), compute_stride(mij_0_tensor, 0)});
    TASSIGN(tmp_gm_0, mij_0 + (0 + 0 * compute_stride(mij_0_tensor, 0) + 0 * compute_stride(mij_0_tensor, 1)));
    TLOAD(mij_tile_0, tmp_gm_0);
    using tmp_gm_1ShapeDim5 = Shape<1, 1, 1, 16, 1>;
    using tmp_gm_1StrideDim5 = Stride<1, 1, 1, -1, -1>;
    using tmp_gm_1Type = GlobalTensor<float, tmp_gm_1ShapeDim5, tmp_gm_1StrideDim5, Layout::DN>;
    tmp_gm_1Type tmp_gm_1(lij_0, {}, {compute_stride(lij_0_tensor, 1), compute_stride(lij_0_tensor, 0)});
    TASSIGN(tmp_gm_1, lij_0 + (0 + 0 * compute_stride(lij_0_tensor, 0) + 0 * compute_stride(lij_0_tensor, 1)));
    TLOAD(lij_tile_0, tmp_gm_1);
    using tmp_gm_2ShapeDim5 = Shape<1, 1, 1, 16, 128>;
    using tmp_gm_2StrideDim5 = Stride<1, 1, 1, -1, -1>;
    using tmp_gm_2Type = GlobalTensor<float, tmp_gm_2ShapeDim5, tmp_gm_2StrideDim5, Layout::ND>;
    tmp_gm_2Type tmp_gm_2(oi_new_0, {}, {compute_stride(oi_new_0_tensor, 0), compute_stride(oi_new_0_tensor, 1)});
    TASSIGN(tmp_gm_2, oi_new_0 + (0 + 0 * compute_stride(oi_new_0_tensor, 0) + 0 * compute_stride(oi_new_0_tensor, 1)));
    TLOAD(oi_new_tile_0, tmp_gm_2);
    using tmp_gm_3ShapeDim5 = Shape<1, 1, 1, 16, 1>;
    using tmp_gm_3StrideDim5 = Stride<1, 1, 1, -1, -1>;
    using tmp_gm_3Type = GlobalTensor<float, tmp_gm_3ShapeDim5, tmp_gm_3StrideDim5, Layout::DN>;
    tmp_gm_3Type tmp_gm_3(mi_0, {}, {compute_stride(mi_0_tensor, 1), compute_stride(mi_0_tensor, 0)});
    TASSIGN(tmp_gm_3, mi_0 + (0 + 0 * compute_stride(mi_0_tensor, 0) + 0 * compute_stride(mi_0_tensor, 1)));
    TLOAD(mi_tile_0, tmp_gm_3);
    using tmp_gm_4ShapeDim5 = Shape<1, 1, 1, 16, 1>;
    using tmp_gm_4StrideDim5 = Stride<1, 1, 1, -1, -1>;
    using tmp_gm_4Type = GlobalTensor<float, tmp_gm_4ShapeDim5, tmp_gm_4StrideDim5, Layout::DN>;
    tmp_gm_4Type tmp_gm_4(li_0, {}, {compute_stride(li_0_tensor, 1), compute_stride(li_0_tensor, 0)});
    TASSIGN(tmp_gm_4, li_0 + (0 + 0 * compute_stride(li_0_tensor, 0) + 0 * compute_stride(li_0_tensor, 1)));
    TLOAD(li_tile_0, tmp_gm_4);
    using tmp_gm_5ShapeDim5 = Shape<1, 1, 1, 16, 128>;
    using tmp_gm_5StrideDim5 = Stride<1, 1, 1, -1, -1>;
    using tmp_gm_5Type = GlobalTensor<float, tmp_gm_5ShapeDim5, tmp_gm_5StrideDim5, Layout::ND>;
    tmp_gm_5Type tmp_gm_5(oi_0, {}, {compute_stride(oi_0_tensor, 0), compute_stride(oi_0_tensor, 1)});
    TASSIGN(tmp_gm_5, oi_0 + (0 + 0 * compute_stride(oi_0_tensor, 0) + 0 * compute_stride(oi_0_tensor, 1)));
    TLOAD(oi_tile_0, tmp_gm_5);
    set_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    wait_flag(PIPE_MTE2, PIPE_MTE3, EVENT_ID0);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    if (is_first_0) {
        using tmp_gm_6ShapeDim5 = Shape<1, 1, 1, 16, 1>;
        using tmp_gm_6StrideDim5 = Stride<1, 1, 1, -1, -1>;
        using tmp_gm_6Type = GlobalTensor<float, tmp_gm_6ShapeDim5, tmp_gm_6StrideDim5, Layout::DN>;
        tmp_gm_6Type tmp_gm_6(mi_0, {}, {compute_stride(mi_0_tensor, 1), compute_stride(mi_0_tensor, 0)});
        TASSIGN(tmp_gm_6, mi_0 + (0 + 0 * compute_stride(mi_0_tensor, 0) + 0 * compute_stride(mi_0_tensor, 1)));
        TSTORE(tmp_gm_6, mij_tile_0);
        using tmp_gm_7ShapeDim5 = Shape<1, 1, 1, 16, 1>;
        using tmp_gm_7StrideDim5 = Stride<1, 1, 1, -1, -1>;
        using tmp_gm_7Type = GlobalTensor<float, tmp_gm_7ShapeDim5, tmp_gm_7StrideDim5, Layout::DN>;
        tmp_gm_7Type tmp_gm_7(li_0, {}, {compute_stride(li_0_tensor, 1), compute_stride(li_0_tensor, 0)});
        TASSIGN(tmp_gm_7, li_0 + (0 + 0 * compute_stride(li_0_tensor, 0) + 0 * compute_stride(li_0_tensor, 1)));
        TSTORE(tmp_gm_7, lij_tile_0);
        using tmp_gm_8ShapeDim5 = Shape<1, 1, 1, 16, 128>;
        using tmp_gm_8StrideDim5 = Stride<1, 1, 1, -1, -1>;
        using tmp_gm_8Type = GlobalTensor<float, tmp_gm_8ShapeDim5, tmp_gm_8StrideDim5, Layout::ND>;
        tmp_gm_8Type tmp_gm_8(oi_0, {}, {compute_stride(oi_0_tensor, 0), compute_stride(oi_0_tensor, 1)});
        TASSIGN(tmp_gm_8, oi_0 + (0 + 0 * compute_stride(oi_0_tensor, 0) + 0 * compute_stride(oi_0_tensor, 1)));
        TSTORE(tmp_gm_8, oi_new_tile_0);
        if (is_last_0) {
            TROWEXPANDDIV(dst_tile_0, oi_new_tile_0, lij_tile_0);
            set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
            wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
            using tmp_gm_9ShapeDim5 = Shape<1, 1, 1, 16, 128>;
            using tmp_gm_9StrideDim5 = Stride<1, 1, 1, -1, -1>;
            using tmp_gm_9Type = GlobalTensor<float, tmp_gm_9ShapeDim5, tmp_gm_9StrideDim5, Layout::ND>;
            tmp_gm_9Type tmp_gm_9(dst_0, {}, {compute_stride(dst_0_tensor, 0), compute_stride(dst_0_tensor, 1)});
            TASSIGN(tmp_gm_9, dst_0 + (0 + 0 * compute_stride(dst_0_tensor, 0) + 0 * compute_stride(dst_0_tensor, 1)));
            TSTORE(tmp_gm_9, dst_tile_0);
        } else {
            TEXPANDS(zero_tile_0, 0.000000);
            using tmp_gm_10ShapeDim5 = Shape<1, 1, 1, 16, 128>;
            using tmp_gm_10StrideDim5 = Stride<1, 1, 1, -1, -1>;
            using tmp_gm_10Type = GlobalTensor<float, tmp_gm_10ShapeDim5, tmp_gm_10StrideDim5, Layout::ND>;
            tmp_gm_10Type tmp_gm_10(dst_0, {}, {compute_stride(dst_0_tensor, 0), compute_stride(dst_0_tensor, 1)});
            TASSIGN(tmp_gm_10, dst_0 + (0 + 0 * compute_stride(dst_0_tensor, 0) + 0 * compute_stride(dst_0_tensor, 1)));
            TSTORE(tmp_gm_10, zero_tile_0);
        }

    } else {
        TRESHAPE(mi_tile_nd_0, mi_tile_0);
        TRESHAPE(mij_tile_nd_0, mij_tile_0);
        TRESHAPE(li_tile_nd_0, li_tile_0);
        TRESHAPE(lij_tile_nd_0, lij_tile_0);
        pipe_barrier(PIPE_V);
        TMAX(mi_new_0, mi_tile_nd_0, mij_tile_nd_0);
        pipe_barrier(PIPE_V);
        TSUB(mi_diff_0, mi_tile_nd_0, mi_new_0);
        pipe_barrier(PIPE_V);
        TEXP(alpha_0, mi_diff_0);
        pipe_barrier(PIPE_V);
        TSUB(mij_diff_0, mij_tile_nd_0, mi_new_0);
        pipe_barrier(PIPE_V);
        TEXP(beta_0, mij_diff_0);
        pipe_barrier(PIPE_V);
        TMUL(li_scaled_0, alpha_0, li_tile_nd_0);
        pipe_barrier(PIPE_V);
        TMUL(lij_scaled_0, beta_0, lij_tile_nd_0);
        pipe_barrier(PIPE_V);
        TADD(li_updated_0, li_scaled_0, lij_scaled_0);
        pipe_barrier(PIPE_V);
        TRESHAPE(alpha_dn_0, alpha_0);
        pipe_barrier(PIPE_V);
        TROWEXPANDMUL(oi_scaled_0, oi_tile_0, alpha_dn_0);
        TRESHAPE(beta_dn_0, beta_0);
        pipe_barrier(PIPE_V);
        TROWEXPANDMUL(oi_new_scaled_0, oi_new_tile_0, beta_dn_0);
        pipe_barrier(PIPE_V);
        TADD(oi_updated_0, oi_scaled_0, oi_new_scaled_0);
        TRESHAPE(mi_new_dn_0, mi_new_0);
        set_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
        pipe_barrier(PIPE_V);
        TRESHAPE(li_updated_dn_0, li_updated_0);
        set_flag(PIPE_V, PIPE_MTE3, EVENT_ID2);
        wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
        using tmp_gm_11ShapeDim5 = Shape<1, 1, 1, 16, 1>;
        using tmp_gm_11StrideDim5 = Stride<1, 1, 1, -1, -1>;
        using tmp_gm_11Type = GlobalTensor<float, tmp_gm_11ShapeDim5, tmp_gm_11StrideDim5, Layout::DN>;
        tmp_gm_11Type tmp_gm_11(mi_0, {}, {compute_stride(mi_0_tensor, 1), compute_stride(mi_0_tensor, 0)});
        TASSIGN(tmp_gm_11, mi_0 + (0 + 0 * compute_stride(mi_0_tensor, 0) + 0 * compute_stride(mi_0_tensor, 1)));
        TSTORE(tmp_gm_11, mi_new_dn_0);
        wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID2);
        using tmp_gm_12ShapeDim5 = Shape<1, 1, 1, 16, 1>;
        using tmp_gm_12StrideDim5 = Stride<1, 1, 1, -1, -1>;
        using tmp_gm_12Type = GlobalTensor<float, tmp_gm_12ShapeDim5, tmp_gm_12StrideDim5, Layout::DN>;
        tmp_gm_12Type tmp_gm_12(li_0, {}, {compute_stride(li_0_tensor, 1), compute_stride(li_0_tensor, 0)});
        TASSIGN(tmp_gm_12, li_0 + (0 + 0 * compute_stride(li_0_tensor, 0) + 0 * compute_stride(li_0_tensor, 1)));
        TSTORE(tmp_gm_12, li_updated_dn_0);
        if (is_last_0) {
            pipe_barrier(PIPE_V);
            TROWEXPANDDIV(dst_tile_1, oi_updated_0, li_updated_dn_0);
            set_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
            wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
            using tmp_gm_13ShapeDim5 = Shape<1, 1, 1, 16, 128>;
            using tmp_gm_13StrideDim5 = Stride<1, 1, 1, -1, -1>;
            using tmp_gm_13Type = GlobalTensor<float, tmp_gm_13ShapeDim5, tmp_gm_13StrideDim5, Layout::ND>;
            tmp_gm_13Type tmp_gm_13(dst_0, {}, {compute_stride(dst_0_tensor, 0), compute_stride(dst_0_tensor, 1)});
            TASSIGN(tmp_gm_13, dst_0 + (0 + 0 * compute_stride(dst_0_tensor, 0) + 0 * compute_stride(dst_0_tensor, 1)));
            TSTORE(tmp_gm_13, dst_tile_1);
            using tmp_gm_14ShapeDim5 = Shape<1, 1, 1, 16, 128>;
            using tmp_gm_14StrideDim5 = Stride<1, 1, 1, -1, -1>;
            using tmp_gm_14Type = GlobalTensor<float, tmp_gm_14ShapeDim5, tmp_gm_14StrideDim5, Layout::ND>;
            tmp_gm_14Type tmp_gm_14(oi_0, {}, {compute_stride(oi_0_tensor, 0), compute_stride(oi_0_tensor, 1)});
            TASSIGN(tmp_gm_14, oi_0 + (0 + 0 * compute_stride(oi_0_tensor, 0) + 0 * compute_stride(oi_0_tensor, 1)));
            TSTORE(tmp_gm_14, oi_updated_0);
        } else {
            TEXPANDS(zero_tile_1, 0.000000);
            using tmp_gm_15ShapeDim5 = Shape<1, 1, 1, 16, 128>;
            using tmp_gm_15StrideDim5 = Stride<1, 1, 1, -1, -1>;
            using tmp_gm_15Type = GlobalTensor<float, tmp_gm_15ShapeDim5, tmp_gm_15StrideDim5, Layout::ND>;
            tmp_gm_15Type tmp_gm_15(dst_0, {}, {compute_stride(dst_0_tensor, 0), compute_stride(dst_0_tensor, 1)});
            TASSIGN(tmp_gm_15, dst_0 + (0 + 0 * compute_stride(dst_0_tensor, 0) + 0 * compute_stride(dst_0_tensor, 1)));
            TSTORE(tmp_gm_15, zero_tile_1);
            using tmp_gm_16ShapeDim5 = Shape<1, 1, 1, 16, 128>;
            using tmp_gm_16StrideDim5 = Stride<1, 1, 1, -1, -1>;
            using tmp_gm_16Type = GlobalTensor<float, tmp_gm_16ShapeDim5, tmp_gm_16StrideDim5, Layout::ND>;
            tmp_gm_16Type tmp_gm_16(oi_0, {}, {compute_stride(oi_0_tensor, 0), compute_stride(oi_0_tensor, 1)});
            TASSIGN(tmp_gm_16, oi_0 + (0 + 0 * compute_stride(oi_0_tensor, 0) + 0 * compute_stride(oi_0_tensor, 1)));
            TSTORE(tmp_gm_16, oi_updated_0);
        }

    }

}
