// Orchestration Function: paged_attention
// Generated by PyPTO IR Compiler

#include "runtime.h"
#include <iostream>

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

#include "pto_orchestration_api.h"

#define ARG_PTR_QUERY 0
#define ARG_PTR_KEY_CACHE 1
#define ARG_PTR_VALUE_CACHE 2
#define ARG_PTR_BLOCK_TABLE 3
#define ARG_PTR_CONTEXT_LENS 4
#define ARG_PTR_OUT 5
#define ARG_PTR_CONFIG 6
#define ARG_PTR_SIZE_QUERY 7
#define ARG_PTR_SIZE_KEY_CACHE 8
#define ARG_PTR_SIZE_VALUE_CACHE 9

// Helper to encode float as uint64_t for scalar params
static uint64_t float_to_u64(float f) {
    union {
        float f32;
        uint64_t u64;
    } conv;
    conv.u64 = 0;  // Clear upper bits
    conv.f32 = f;
    return conv.u64;
}

extern "C" {

__attribute__((visibility("default")))
PTO2OrchestrationConfig aicpu_orchestration_config(uint64_t* args, int arg_count) {
    (void)args;
    (void)arg_count;
    return PTO2OrchestrationConfig{
        .expected_arg_count = 10,
    };
}


static inline Tensor make_tensor_external_2d_dn(void* addr,
    const uint64_t shapes[],
    uint64_t ndims,
    DataType dtype = DataType::FLOAT32,
    int32_t version = 0) {
    debug_assert(ndims == 2);
    static uint64_t zero_offsets[RUNTIME_MAX_TENSOR_DIMS] = {};
    uint64_t total = 1;
    for (uint64_t i = 0; i < ndims; i++) {
        total *= shapes[i];
    }
    uint64_t raw_shapes[RUNTIME_MAX_TENSOR_DIMS] = {shapes[1], shapes[0]};
    return Tensor(addr, total * get_element_size(dtype),
        raw_shapes, shapes, zero_offsets, ndims, dtype, version);
}

static inline Tensor make_tensor_2d_dn(
    const uint64_t shapes[],
    uint64_t ndims,
    DataType dtype = DataType::FLOAT32,
    int32_t version = 0) {
    debug_assert(ndims == 2);
    static uint64_t zero_offsets[RUNTIME_MAX_TENSOR_DIMS] = {};
    uint64_t total = 1;
    for (uint64_t i = 0; i < ndims; i++) {
        total *= shapes[i];
    }
    uint64_t raw_shapes[RUNTIME_MAX_TENSOR_DIMS] = {shapes[1], shapes[0]};
    return Tensor(0, total * get_element_size(dtype),
        raw_shapes, shapes, zero_offsets, ndims, dtype, version);
}

__attribute__((visibility("default")))
void aicpu_orchestration_entry(PTO2Runtime* rt, uint64_t* args, int arg_count, int orch_thread_num, int orch_thread_index) {
    (void)arg_count;
    (void)orch_thread_num;
    (void)orch_thread_index;

    // Extract device pointers
    void* arg_query_ptr = reinterpret_cast<void*>(args[ARG_PTR_QUERY]);
    void* arg_key_cache_ptr = reinterpret_cast<void*>(args[ARG_PTR_KEY_CACHE]);
    void* arg_value_cache_ptr = reinterpret_cast<void*>(args[ARG_PTR_VALUE_CACHE]);
    void* arg_block_table_ptr = reinterpret_cast<void*>(args[ARG_PTR_BLOCK_TABLE]);
    void* arg_context_lens_ptr = reinterpret_cast<void*>(args[ARG_PTR_CONTEXT_LENS]);
    void* arg_out_ptr = reinterpret_cast<void*>(args[ARG_PTR_OUT]);
    void* arg_config_ptr = reinterpret_cast<void*>(args[ARG_PTR_CONFIG]);
    void* arg_size_query_ptr = reinterpret_cast<void*>(args[ARG_PTR_SIZE_QUERY]);
    void* arg_size_key_cache_ptr = reinterpret_cast<void*>(args[ARG_PTR_SIZE_KEY_CACHE]);
    void* arg_size_value_cache_ptr = reinterpret_cast<void*>(args[ARG_PTR_SIZE_VALUE_CACHE]);

    // External tensors
    uint64_t query_shapes[2] = {1024, 128};
    Tensor ext_query = make_tensor_external(arg_query_ptr, query_shapes, 2, DataType::BFLOAT16);
    uint64_t key_cache_shapes[2] = {128, 2097152};
    Tensor ext_key_cache = make_tensor_external_2d_dn(arg_key_cache_ptr, key_cache_shapes, 2, DataType::BFLOAT16);
    uint64_t value_cache_shapes[2] = {2097152, 128};
    Tensor ext_value_cache = make_tensor_external(arg_value_cache_ptr, value_cache_shapes, 2, DataType::BFLOAT16);
    uint64_t block_table_shapes[1] = {16384};
    Tensor ext_block_table = make_tensor_external(arg_block_table_ptr, block_table_shapes, 1, DataType::INT32);
    uint64_t context_lens_shapes[1] = {64};
    Tensor ext_context_lens = make_tensor_external(arg_context_lens_ptr, context_lens_shapes, 1, DataType::INT32);
    uint64_t out_shapes[2] = {1024, 128};
    Tensor ext_out = make_tensor_external(arg_out_ptr, out_shapes, 2, DataType::FLOAT32);
    uint64_t config_shapes[1] = {7};
    Tensor ext_config = make_tensor_external(arg_config_ptr, config_shapes, 1, DataType::INT64);
    uint64_t size_query_shapes[1] = {1};
    Tensor ext_size_query = make_tensor_external(arg_size_query_ptr, size_query_shapes, 1, DataType::INT64);
    uint64_t size_key_cache_shapes[1] = {1};
    Tensor ext_size_key_cache = make_tensor_external(arg_size_key_cache_ptr, size_key_cache_shapes, 1, DataType::INT64);
    uint64_t size_value_cache_shapes[1] = {1};
    Tensor ext_size_value_cache = make_tensor_external(arg_size_value_cache_ptr, size_value_cache_shapes, 1, DataType::INT64);

    int64_t batch_cfg = static_cast<int64_t*>(arg_config_ptr)[0];
    int64_t num_heads_cfg = static_cast<int64_t*>(arg_config_ptr)[1];
    int64_t head_dim_cfg = static_cast<int64_t*>(arg_config_ptr)[3];
    int64_t block_size_cfg = static_cast<int64_t*>(arg_config_ptr)[4];
    int64_t block_num_cfg = static_cast<int64_t*>(arg_config_ptr)[5];
    int64_t q_head_num = num_heads_cfg;
    int64_t q_loop_cfg = (((q_head_num + 16) - 1) / 16);
    for (int64_t b_idx = 0; b_idx < batch_cfg; b_idx += 1) {
        PTO2_SCOPE(rt) {
            size_t idx_cur_seq = b_idx;
            int32_t cur_seq = static_cast<int32_t*>(arg_context_lens_ptr)[idx_cur_seq];
            int64_t bn_this_batch = (((static_cast<int64_t>(cur_seq) + block_size_cfg) - 1) / block_size_cfg);
            for (int64_t q_idx = 0; q_idx < q_loop_cfg; q_idx += 1) {
                PTO2_SCOPE(rt) {
                    int64_t cur_offset = ((b_idx * q_head_num) + (q_idx * 16));
                    uint64_t oi_shapes[2] = {16, head_dim_cfg};
                    Tensor oi = make_tensor(oi_shapes, 2, DataType::FLOAT32);
                    uint64_t li_update_shapes[2] = {16, 1};
                    Tensor li_update = make_tensor(li_update_shapes, 2, DataType::FLOAT32);
                    uint64_t mi_update_shapes[2] = {16, 1};
                    Tensor mi_update = make_tensor(mi_update_shapes, 2, DataType::FLOAT32);

                    // Task 0: kernel_init_inplace
                    PTOParam params_t0[] = {
                        make_output_param(oi),
                        make_output_param(li_update),
                        make_output_param(mi_update),
                    };
                    pto2_rt_submit_aiv_task(rt, 0, params_t0, 3);
                    for (int64_t bn = 0; bn < bn_this_batch; bn += 1) {
                        PTO2_SCOPE(rt) {
                            uint64_t qi_shapes[2] = {16, head_dim_cfg};
                            uint64_t qi_offsets[2] = {cur_offset, 0};
                            Tensor qi = ext_query.view(qi_shapes, qi_offsets);
                            size_t idx_cur_block_idx = ((b_idx * block_num_cfg) + bn);
                            int32_t cur_block_idx = static_cast<int32_t*>(arg_block_table_ptr)[idx_cur_block_idx];
                            int64_t valid_len = std::min<int64_t>(block_size_cfg, (static_cast<int64_t>(cur_seq) - (bn * block_size_cfg)));
                            int64_t kv_block_row = (static_cast<int64_t>(cur_block_idx) * block_size_cfg);
                            uint64_t kj_shapes[2] = {head_dim_cfg, block_size_cfg};
                            uint64_t kj_offsets[2] = {kv_block_row, 0};
                            Tensor kj = ext_key_cache.view(kj_shapes, kj_offsets);
                            uint64_t vj_shapes[2] = {block_size_cfg, head_dim_cfg};
                            uint64_t vj_offsets[2] = {kv_block_row, 0};
                            Tensor vj = ext_value_cache.view(vj_shapes, vj_offsets);
                            uint64_t sij_shapes[2] = {16, block_size_cfg};
                            Tensor sij = make_tensor(sij_shapes, 2, DataType::FLOAT32);

                            // Task 1: kernel_qk_matmul
                            PTOParam params_t1[] = {
                                make_input_param(qi),
                                make_input_param(kj),
                                make_output_param(sij),
                            };
                            pto2_rt_submit_aic_task(rt, 1, params_t1, 3);
                            uint64_t sij_valid_shapes[2] = {16, valid_len};
                            uint64_t sij_valid_offsets[2] = {0, 0};
                            Tensor sij_valid = sij.view(sij_valid_shapes, sij_valid_offsets);
                            uint64_t pij_f16_shapes[2] = {16, block_size_cfg};
                            Tensor pij_f16 = make_tensor(pij_f16_shapes, 2, DataType::BFLOAT16);
                            uint64_t mi_shapes[2] = {16, 1};
                            Tensor mi = make_tensor(mi_shapes, 2, DataType::FLOAT32);
                            uint64_t li_shapes[2] = {16, 1};
                            Tensor li = make_tensor(li_shapes, 2, DataType::FLOAT32);

                            // Task 2: kernel_softmax_prepare
                            PTOParam params_t2[] = {
                                make_input_param(sij_valid),
                                make_scalar_param(float_to_u64(1.000000f)),
                                make_output_param(pij_f16),
                                make_output_param(mi),
                                make_output_param(li),
                            };
                            pto2_rt_submit_aiv_task(rt, 2, params_t2, 5);
                            uint64_t oi_tmp_shapes[2] = {16, head_dim_cfg};
                            Tensor oi_tmp = make_tensor(oi_tmp_shapes, 2, DataType::FLOAT32);

                            // Task 3: kernel_pv_matmul
                            PTOParam params_t3[] = {
                                make_input_param(pij_f16),
                                make_input_param(vj),
                                make_output_param(oi_tmp),
                            };
                            pto2_rt_submit_aic_task(rt, 3, params_t3, 3);
                            int64_t is_first;
                            if ((bn == 0)) {
                                PTO2_SCOPE(rt) {
                                    is_first = 1;
                                }
                            } else {
                                PTO2_SCOPE(rt) {
                                    is_first = 0;
                                }
                            }
                            int64_t is_last;
                            if ((bn == (bn_this_batch - 1))) {
                                PTO2_SCOPE(rt) {
                                    is_last = 1;
                                }
                            } else {
                                PTO2_SCOPE(rt) {
                                    is_last = 0;
                                }
                            }
                            uint64_t out_view_shapes[2] = {16, head_dim_cfg};
                            uint64_t out_view_offsets[2] = {cur_offset, 0};
                            Tensor out_view = ext_out.view(out_view_shapes, out_view_offsets);

                            // Task 4: kernel_online_update
                            PTOParam params_t4[] = {
                                make_input_param(mi),
                                make_input_param(li),
                                make_input_param(oi_tmp),
                                make_inout_param(mi_update),
                                make_inout_param(li_update),
                                make_inout_param(oi),
                                make_output_param(out_view),
                                make_scalar_param(is_first),
                                make_scalar_param(is_last),
                            };
                            pto2_rt_submit_aiv_task(rt, 4, params_t4, 9);
                        }
                    }
                }
            }
        }
    }
}

}  // extern "C"
