"""
Auto-generated golden script — do not edit by hand.

Generated by pypto.runtime.golden_writer
"""

import ctypes
import struct
import torch

__outputs__ = ['out']
RTOL = 0.02
ATOL = 0.02

def generate_inputs(params):
    """Generate inputs as a list of (name, value) tuples."""
    query = torch.randn((1024, 128), dtype=torch.bfloat16)
    key_cache = torch.randn((2097152, 128), dtype=torch.bfloat16)
    value_cache = torch.randn((2097152, 128), dtype=torch.bfloat16)
    block_table = torch.zeros((16384,), dtype=torch.int32)  # WARNING: tensor too large (16384 elements) to inline; replace with actual data.
    context_lens = torch.full((64,), 8192, dtype=torch.int32)
    out = torch.zeros((1024, 128), dtype=torch.float32)
    config = torch.tensor([64, 16, 1, 128, 128, 256, 1065353216], dtype=torch.int64)
    size_query = torch.full((1,), 262144, dtype=torch.int64)
    size_key_cache = torch.full((1,), 536870912, dtype=torch.int64)
    size_value_cache = torch.full((1,), 536870912, dtype=torch.int64)

    return [
        ("query", query),
        ("key_cache", key_cache),
        ("value_cache", value_cache),
        ("block_table", block_table),
        ("context_lens", context_lens),
        ("out", out),
        ("config", config),
        ("size_query", size_query),
        ("size_key_cache", size_key_cache),
        ("size_value_cache", size_value_cache),
        ("size_query", ctypes.c_int64(query.nbytes)),
        ("size_key_cache", ctypes.c_int64(key_cache.nbytes)),
        ("size_value_cache", ctypes.c_int64(value_cache.nbytes)),
        ("size_block_table", ctypes.c_int64(block_table.nbytes)),
        ("size_context_lens", ctypes.c_int64(context_lens.nbytes)),
        ("size_out", ctypes.c_int64(out.nbytes)),
        ("size_config", ctypes.c_int64(config.nbytes)),
        ("size_size_query", ctypes.c_int64(size_query.nbytes)),
        ("size_size_key_cache", ctypes.c_int64(size_key_cache.nbytes)),
        ("size_size_value_cache", ctypes.c_int64(size_value_cache.nbytes)),
    ]


def compute_golden(tensors, params=None):
    config = tensors["config"]
    batch = int(config[0].item())
    num_heads = int(config[1].item())
    head_dim = int(config[3].item())
    block_size = int(config[4].item())
    max_num_blocks_per_req = int(config[5].item())
    scale_bits = int(config[6].item())
    scale_value = struct.unpack("f", struct.pack("I", scale_bits & 0xFFFFFFFF))[0]

    query = tensors["query"].float().reshape(batch, num_heads, head_dim)
    total_pool_blocks = batch * max_num_blocks_per_req
    key_cache = tensors["key_cache"].float().reshape(total_pool_blocks, block_size, head_dim)
    value_cache = tensors["value_cache"].float().reshape(total_pool_blocks, block_size, head_dim)
    block_table = tensors["block_table"].reshape(batch, max_num_blocks_per_req)
    context_lens = tensors["context_lens"]

    out = torch.zeros((batch, num_heads, head_dim), dtype=torch.float32)
    q_tile = 16
    max_bn = int((context_lens.max().item() + block_size - 1) // block_size)

    for q_offset in range(0, num_heads, q_tile):
        q_tile_size = min(q_tile, num_heads - q_offset)
        qi = query[:, q_offset : q_offset + q_tile_size, :]
        oi, li, mi = None, None, None

        for bn in range(max_bn):
            valid_lens = torch.clamp(context_lens - bn * block_size, min=0, max=block_size)
            if not (valid_lens > 0).any():
                break
            block_indices = block_table[:, bn]
            kj_all = key_cache[block_indices].float()
            vj_all = value_cache[block_indices].float()
            sij = torch.bmm(qi, kj_all.transpose(1, 2)) * scale_value
            pos = torch.arange(block_size).unsqueeze(0)
            valid_mask = (pos < valid_lens.unsqueeze(1)).unsqueeze(1)
            sij = sij.masked_fill(~valid_mask, float("-inf"))
            mij = sij.max(dim=-1, keepdim=True)[0].clamp(min=-1e30)
            pij = torch.exp(sij - mij).masked_fill(~valid_mask, 0.0)
            pij = pij.to(torch.bfloat16).to(torch.float32)
            lij = pij.sum(dim=-1, keepdim=True)
            oi_new = torch.bmm(pij, vj_all)
            if bn == 0:
                oi, li, mi = oi_new, lij, mij
            else:
                mi_new = torch.maximum(mi, mij)
                alpha = torch.exp(mi - mi_new)
                beta = torch.exp(mij - mi_new)
                li = alpha * li + beta * lij
                oi = alpha * oi + beta * oi_new
                mi = mi_new

        out[:, q_offset : q_offset + q_tile_size, :] = oi / li

    tensors["out"][:] = out.reshape(batch * num_heads, head_dim)
