// Kernel Function: kernel_pv_matmul
// Generated by PyPTO IR Compiler


#include <cstdint>
#include <pto/pto-inst.hpp>
#include "tensor.h"

using namespace pto;

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#define __aicore__ [aicore]
#endif

// Helper function to compute stride from raw_shapes
__aicore__ __attribute__((always_inline)) inline int64_t compute_stride(
    __gm__ TensorData* tensor, int dim) {
  int64_t stride = 1;
  for (int j = dim + 1; j < static_cast<int>(tensor->ndims); j++) {
    stride *= static_cast<int64_t>(tensor->raw_shapes[j]);
  }
  return stride;
}

extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack arguments and type declarations
    __gm__ TensorData* pij_0_tensor = reinterpret_cast<__gm__ TensorData*>(args[0]);
    __gm__ bfloat16_t* pij_0 = reinterpret_cast<__gm__ bfloat16_t*>(pij_0_tensor->buffer.addr) + pij_0_tensor->start_offset;

    __gm__ TensorData* vj_0_tensor = reinterpret_cast<__gm__ TensorData*>(args[1]);
    __gm__ bfloat16_t* vj_0 = reinterpret_cast<__gm__ bfloat16_t*>(vj_0_tensor->buffer.addr) + vj_0_tensor->start_offset;

    __gm__ TensorData* output_0_tensor = reinterpret_cast<__gm__ TensorData*>(args[2]);
    __gm__ float* output_0 = reinterpret_cast<__gm__ float*>(output_0_tensor->buffer.addr) + output_0_tensor->start_offset;

    // Tile type definitions and allocations
    using pij_l1_0Type = Tile<TileType::Mat, bfloat16_t, 16, 128, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512>;
    pij_l1_0Type pij_l1_0(16, 128);
    TASSIGN(pij_l1_0, 0x0);
    using vj_l1_0Type = Tile<TileType::Mat, bfloat16_t, 128, 128, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512>;
    vj_l1_0Type vj_l1_0(128, 128);
    TASSIGN(vj_l1_0, 0x1000);
    using pij_l0a_0Type = Tile<TileType::Left, bfloat16_t, 16, 128, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512>;
    pij_l0a_0Type pij_l0a_0(16, 128);
    TASSIGN(pij_l0a_0, 0x0);
    using vj_l0b_0Type = Tile<TileType::Right, bfloat16_t, 128, 128, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512>;
    vj_l0b_0Type vj_l0b_0(128, 128);
    TASSIGN(vj_l0b_0, 0x0);
    using oi_l0c_0Type = Tile<TileType::Acc, float, 16, 128, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024>;
    oi_l0c_0Type oi_l0c_0(16, 128);
    TASSIGN(oi_l0c_0, 0x0);


    // Function body
    using tmp_gm_0ShapeDim5 = Shape<1, 1, 1, 16, 128>;
    using tmp_gm_0StrideDim5 = Stride<1, 1, 1, -1, -1>;
    using tmp_gm_0Type = GlobalTensor<bfloat16_t, tmp_gm_0ShapeDim5, tmp_gm_0StrideDim5, Layout::ND>;
    tmp_gm_0Type tmp_gm_0(pij_0, {}, {compute_stride(pij_0_tensor, 0), compute_stride(pij_0_tensor, 1)});
    TASSIGN(tmp_gm_0, pij_0 + (0 + 0 * compute_stride(pij_0_tensor, 0) + 0 * compute_stride(pij_0_tensor, 1)));
    TLOAD(pij_l1_0, tmp_gm_0);
    set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID0);
    using tmp_gm_1ShapeDim5 = Shape<1, 1, 1, 128, 128>;
    using tmp_gm_1StrideDim5 = Stride<1, 1, 1, -1, -1>;
    using tmp_gm_1Type = GlobalTensor<bfloat16_t, tmp_gm_1ShapeDim5, tmp_gm_1StrideDim5, Layout::ND>;
    tmp_gm_1Type tmp_gm_1(vj_0, {}, {compute_stride(vj_0_tensor, 0), compute_stride(vj_0_tensor, 1)});
    TASSIGN(tmp_gm_1, vj_0 + (0 + 0 * compute_stride(vj_0_tensor, 0) + 0 * compute_stride(vj_0_tensor, 1)));
    TLOAD(vj_l1_0, tmp_gm_1);
    set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID1);
    wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID0);
    TMOV(pij_l0a_0, pij_l1_0);
    wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID1);
    TMOV(vj_l0b_0, vj_l1_0);
    set_flag(PIPE_MTE1, PIPE_M, EVENT_ID0);
    wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID0);
    TMATMUL(oi_l0c_0, pij_l0a_0, vj_l0b_0);
    set_flag(PIPE_M, PIPE_FIX, EVENT_ID0);
    wait_flag(PIPE_M, PIPE_FIX, EVENT_ID0);
    using tmp_gm_2ShapeDim5 = Shape<1, 1, 1, 16, 128>;
    using tmp_gm_2StrideDim5 = Stride<1, 1, 1, -1, -1>;
    using tmp_gm_2Type = GlobalTensor<float, tmp_gm_2ShapeDim5, tmp_gm_2StrideDim5, Layout::ND>;
    tmp_gm_2Type tmp_gm_2(output_0, {}, {compute_stride(output_0_tensor, 0), compute_stride(output_0_tensor, 1)});
    TASSIGN(tmp_gm_2, output_0 + (0 + 0 * compute_stride(output_0_tensor, 0) + 0 * compute_stride(output_0_tensor, 1)));
    TSTORE(tmp_gm_2, oi_l0c_0);
}
